from enum import StrEnum


class ProjectStatus(StrEnum):
    DRAFT = "DRAFT"
    ANALYZING = "ANALYZING"
    AWAITING_ASSET_APPROVAL = "AWAITING_ASSET_APPROVAL"
    READY = "READY"
    PRODUCING = "PRODUCING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StageStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    OUTPUT_READY = "OUTPUT_READY"
    COMPLETED = "COMPLETED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    CANCELLED = "CANCELLED"
    STALE = "STALE"
    ADOPTED = "ADOPTED"
